Rename modified functions in localcharset.c
This avoids problems with static builds: Gnulib's localcharset.c may
be compiled into multiple library archives. In general, that works
fine because the linker only pulls in object files that are needed
to satisfy an unresolved symbol. Once provided, all future files and
definitions will be ignored.
However, Guile's modified localcharset.c also provided the related
function environ_locale_charset. Because that function is referenced
and not provided by any other archive, the linker is forced to include
Guile's copy of localcharset.c. This can lead to duplicate symbols for
locale_charset if another archive already provided it:

/usr/bin/ld: libguile-3.0.a(libgnu_la-localcharset.o): in function `locale_charset':
guile-3.0.11/lib/localcharset.c:832: multiple definition of `locale_charset';
libunistring.a(libunistring_la-localcharset.o):
libunistring-1.4.1/lib/localcharset.c:793: first defined here

* gnulib-local/lib/lc-charset-dispatch.c.diff: Add.
* gnulib-local/lib/localcharset.c.diff:
* gnulib-local/lib/localcharset.h.diff: Rename modified functions.
* gnulib-local/lib/vasnprintf.c.diff: Add.
* lib/lc-charset-dispatch.c: Call renamed scm_i_local_charset.
* lib/localcharset.c:
* lib/localcharset.h: Rename modified functions.
* lib/vasnprintf.c: Call renamed scm_i_local_charset.
* libguile/ports.c:
* libguile/posix.c:
* libguile/script.c:
* libguile/strings.c: Call renamed functions.
* test-suite/standalone/test-command-line-encoding:
* test-suite/standalone/test-command-line-encoding2: Update comment.