boot-9: Cleanup implementation of `define-values'
This was fixed by commit 0fd9ee8fc9e3e1a7fa9dd91b78e4c3ba2b870f39.

Before that, the new tests introduced by this commit would fail with:

  ERROR: syntax.test: top-level define-values: hygiene: binding named dummy - arguments: ((unbound-variable "module-lookup" "Unbound variable: ~S" (dummy) #f))
  ERROR: syntax.test: top-level define-values: hygiene: does not shadow outer dummy - arguments: ((unbound-variable "module-lookup" "Unbound variable: ~S" (dummy) #f))

* module/ice-9/boot-9.scm (define-values): Remove stale
generate-temporaries workaround for missing hygiene top-level
identifier.
* test-suite/tests/syntax.test: New regression tests for testing hygiene
of `define-values'.

Signed-off-by: Olivier Dion <olivier.dion@polymtl.ca>