Use scm_t_ptrdiff consistently instead of ptrdiff_t
This fixes the following errors in a MinGW cross-build.

libtool: compile:  i586-mingw32msvc-gcc -DHAVE_CONFIG_H -I.. -I.. -I.. -I/usr/local/i586-mingw32msvc/include -I/usr/local/i586-mingw32msvc/include -g -O2 -Wall -Wmissing-prototypes -Werror -MT libguile_la-discouraged.lo -MD -MP -MF .deps/libguile_la-discouraged.Tpo -c discouraged.c  -DDLL_EXPORT -DPIC -o .libs/libguile_la-discouraged.o
discouraged.c:75: error: conflicting types for 'scm_ptrdiff2num'
../libguile/discouraged.h:75: error: previous declaration of 'scm_ptrdiff2num' was here
discouraged.c:123: error: conflicting types for 'scm_num2ptrdiff'
../libguile/discouraged.h:89: error: previous declaration of 'scm_num2ptrdiff' was here

* libguile/discouraged.c (scm_ptrdiff2num, scm_num2ptrdiff): Use
  scm_t_ptrdiff instead of ptrdiff_t.